# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20160910_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(default='none', max_length=100)),
                ('Status', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.RemoveField(
            model_name='equipments',
            name='availability',
        ),
        migrations.AddField(
            model_name='equipments',
            name='Mentor',
            field=models.CharField(default='hello', max_length=30),
        ),
        migrations.AddField(
            model_name='equipments',
            name='MentorEmail',
            field=models.CharField(default='hello', max_length=100),
        ),
        migrations.AddField(
            model_name='equipments',
            name='TotalTaken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipmentstatus',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Equipments'),
        ),
    ]
