# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 01:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20160911_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentstatus',
            name='UserId',
            field=models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
